### PR TITLE
Github actions instead of Travis and homebrew badge

### PR DESCRIPTION
**Pull request by organom**
Github actions instead of Travis and homebrew badge

What was done:
- .travis.yml file removed
- same code logic (install and test) applied to github actions, from gcc 6 to 10 and from clang 6 to 10
- changed travis badge to github actions badge
- added homebrew badge

### CODE REVIEW

**Comment by ilyash** [comment]
Thanks!

* Is there any way to make the "matrix" more elegant than listing explicitly each OS * each compiler?
* Can this be tested before merge? Asking because I expect it to break due to https://github.com/ngs-lang/ngs/issues/345

**Comment by organom** [comment]
Tested on my local branch https://github.com/organom/ngs/actions

Did it descriptive like this so that later we can add different versions / flavors of linux and macOS. Lets talk on what makes sense to include and what we should drop and then we can easily add it :)

**Comment by organom** [comment]
@ilyash Added macOS run with clang and gcc as we talked about :)  
code mainly based on: https://github.com/onqtam/doctest/pull/285/files
test run can be found here: https://github.com/organom/ngs/actions/runs/261337703

**Comment by organom** [comment]
@ilyash Added also the debian run that we talked about. Had to separate it into a different "build" section, because this one uses a `container` that is not hosted by github. Made multiple tries to have it together but without success, mainly because github actions don't allow conditional (if) in the container section.

**Comment by ilyash** [comment]
Thanks!

**Pull request merged**
